Lab2 PR
TheLostLegend/CrystalCave pull request #1
Opened 2022-03-12 13:59 UTC by TheLostLegend

Проверьте пожалуйста разметку.

2022-03-13 19:35 UTC, Nastik1811 commented
Я всё ещё не вижу html-разметки на макете

2022-03-13 19:51 UTC, Nastik1811 commented
И сделайте удобочитаемое, пожалуйста, описание проекта. По крайней мере проверьте разметку и опечатки

2022-03-17 18:40 UTC, Nastik1811 requested changes
Смотрите комментарии выше

2022-03-17 22:50 UTC, TheLostLegend commented
Изменен readme и разделение в фигме превращено в нечто более похожее на html. Посмотрите пожалуйста.

2022-03-18 17:21 UTC, Nastik1811 commented
А вы можете ссылкой макет прикрепить?

2022-03-18 17:22 UTC, TheLostLegend commented
Если прикреплять макет ссылкой, то выглядеть он будет так 
https://www.figma.com/file/EMh4KE9cDJtLPx9bUseVBi/Lab2_1-(1)?node-id=1%3A2

2022-03-18 17:22 UTC, Nastik1811 commented
readme всё ещё не удовлетворительный.

2022-03-18 17:25 UTC, TheLostLegend commented
Можете скинуть пример readme? Тк я не совсем понимаю что еще нужно сделать, дабы он стал удовлетворительным

2022-03-18 21:47 UTC, Nastik1811 commented
<img width="863" alt="image" src="https://user-images.githubusercontent.com/37243282/159087048-77f92bc9-436b-43ec-84d9-2faf2c25da62.png">

2022-03-18 22:30 UTC, TheLostLegend commented
Ну, вроде бы сделал. Как вам?

2022-03-19 07:39 UTC, Nastik1811 commented
Да, намного лучше!
На данный момент могу предложить вам `6`. 
Достаточно или хотите повысить?

2022-03-19 12:33 UTC, TheLostLegend commented
Что мне доделать/дополнить до 7-8? Вроде бы частично этот пункт выполнен

2022-03-19 14:45 UTC, Nastik1811 commented
Добавьте заголовки, пересмотрите использование `<span>`, добавьте `<form>` и `<main>`, где нужно. И посмотрите комментарии в фигме.

2022-03-19 16:33 UTC, TheLostLegend commented
Я поправил вроде все, что сказали. А качестве фишки для всех пользователей будет гайд (патерн нажатий на кнопки написанный на джаваскрипте) на "идеальную" игру песни. Если играть не умеешь, можно послушать и посмотреть в качестве примера как можно играть(в гайде кнопки на экране так же подсвечиваются, будто играет сам пользователь).

2022-03-20 07:36 UTC, Nastik1811 commented
Поправь ещё несколько мест (оставила комментарии в фигме) и могу поставить `7`. 
В дальнейшем за счёт функционала можешь выйти на более высокую оценку.

2022-03-20 10:09 UTC, TheLostLegend commented
Все поправил, согласен на 7.

2022-03-21 12:17 UTC, Nastik1811 approved these changes

2022-04-21 10:37 UTC, merged